// default package
// Generated 2018-4-1 21:37:58 by Hibernate Tools 5.2.8.Final
package src.net.bittreasury.fts.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * FtsCategories generated by hbm2java
 */
public class FtsCategories implements java.io.Serializable {

	private Integer id;
	private FtsCategories ftsCategories;
	private String name;
	private int locked;
	private Set ftsCategorieses = new HashSet(0);
	private Set ftsResources = new HashSet(0);
	private Set ftsOriginalResources = new HashSet(0);

	public FtsCategories() {
	}

	public FtsCategories(FtsCategories ftsCategories, String name, int locked) {
		this.ftsCategories = ftsCategories;
		this.name = name;
		this.locked = locked;
	}

	public FtsCategories(FtsCategories ftsCategories, String name, int locked, Set ftsCategorieses, Set ftsResources,
			Set ftsOriginalResources) {
		this.ftsCategories = ftsCategories;
		this.name = name;
		this.locked = locked;
		this.ftsCategorieses = ftsCategorieses;
		this.ftsResources = ftsResources;
		this.ftsOriginalResources = ftsOriginalResources;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FtsCategories getFtsCategories() {
		return this.ftsCategories;
	}

	public void setFtsCategories(FtsCategories ftsCategories) {
		this.ftsCategories = ftsCategories;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getLocked() {
		return this.locked;
	}

	public void setLocked(int locked) {
		this.locked = locked;
	}

	public Set getFtsCategorieses() {
		return this.ftsCategorieses;
	}

	public void setFtsCategorieses(Set ftsCategorieses) {
		this.ftsCategorieses = ftsCategorieses;
	}

	public Set getFtsResources() {
		return this.ftsResources;
	}

	public void setFtsResources(Set ftsResources) {
		this.ftsResources = ftsResources;
	}

	public Set getFtsOriginalResources() {
		return this.ftsOriginalResources;
	}

	public void setFtsOriginalResources(Set ftsOriginalResources) {
		this.ftsOriginalResources = ftsOriginalResources;
	}

}
