// default package
// Generated 2018-4-1 21:37:58 by Hibernate Tools 5.2.8.Final
package src.net.bittreasury.fts.domain;

/**
 * FtsOriginalResource generated by hbm2java
 */
public class FtsOriginalResource implements java.io.Serializable {

	private Integer id;
	private FtsCategories ftsCategories;
	private String name;
	private String description;
	private String imageUrl;
	private String resourceUrl;
	private int insertTime;
	private int downloads;
	private int pageViews;
	private int locked;

	public FtsOriginalResource() {
	}

	public FtsOriginalResource(FtsCategories ftsCategories, String name, String resourceUrl, int insertTime,
			int downloads, int pageViews, int locked) {
		this.ftsCategories = ftsCategories;
		this.name = name;
		this.resourceUrl = resourceUrl;
		this.insertTime = insertTime;
		this.downloads = downloads;
		this.pageViews = pageViews;
		this.locked = locked;
	}

	public FtsOriginalResource(FtsCategories ftsCategories, String name, String description, String imageUrl,
			String resourceUrl, int insertTime, int downloads, int pageViews, int locked) {
		this.ftsCategories = ftsCategories;
		this.name = name;
		this.description = description;
		this.imageUrl = imageUrl;
		this.resourceUrl = resourceUrl;
		this.insertTime = insertTime;
		this.downloads = downloads;
		this.pageViews = pageViews;
		this.locked = locked;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FtsCategories getFtsCategories() {
		return this.ftsCategories;
	}

	public void setFtsCategories(FtsCategories ftsCategories) {
		this.ftsCategories = ftsCategories;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	public int getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(int insertTime) {
		this.insertTime = insertTime;
	}

	public int getDownloads() {
		return this.downloads;
	}

	public void setDownloads(int downloads) {
		this.downloads = downloads;
	}

	public int getPageViews() {
		return this.pageViews;
	}

	public void setPageViews(int pageViews) {
		this.pageViews = pageViews;
	}

	public int getLocked() {
		return this.locked;
	}

	public void setLocked(int locked) {
		this.locked = locked;
	}

}
