// default package
// Generated 2018-4-1 21:37:58 by Hibernate Tools 5.2.8.Final

package src.net.bittreasury.fts.domain;

/**
 * FtsUsers generated by hbm2java
 */
public class FtsUsers implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private String email;
	private int locked;
	private Integer phoneNumber;
	private int userType;
	private String collections;

	public FtsUsers() {
	}

	public FtsUsers(String userName, String password, String email, int locked, int userType) {
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.locked = locked;
		this.userType = userType;
	}

	public FtsUsers(String userName, String password, String email, int locked, Integer phoneNumber, int userType,
			String collections) {
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.locked = locked;
		this.phoneNumber = phoneNumber;
		this.userType = userType;
		this.collections = collections;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getLocked() {
		return this.locked;
	}

	public void setLocked(int locked) {
		this.locked = locked;
	}

	public Integer getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Integer phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public int getUserType() {
		return this.userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	public String getCollections() {
		return this.collections;
	}

	public void setCollections(String collections) {
		this.collections = collections;
	}

}
